version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - proxy-net

  proxy-pool:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - proxy-net

volumes:
  redis_data:

networks:
  proxy-net:
