version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - proxy-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  proxy-pool:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - LOG_LEVEL=INFO
      - CRAWL_TIMEOUT=30
      - MAX_PROXIES=1000
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - proxy-net
    command: uvicorn run:app --host 0.0.0.0 --port 8000

  crawler:
    build: .
    environment:
      - REDIS_HOST=redis
      - LOG_LEVEL=INFO
      - CRAWL_TIMEOUT=30
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - proxy-net
    command: python run.py --crawl

volumes:
  redis_data:

networks:
  proxy-net:
    driver: bridge
